#   aws_region                     = ap-south-1
project_name                   = "hcl"
environment                    = "dev"
vpc_cidr                       = "10.4.0.0/16"
subnet_azs                     = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]1
public_subnets                 = ["10.4.3.0/24", "10.4.4.0/24", "10.4.5.0/24" ]
single_nat_gateway             = true
one_nat_gateway_per_az         = false
instance_type                  = "t2.micro"