name: Folder Creation Workflows

on:
  workflow_call:
    
jobs:
  deploy:
    name: 'create-folder-structure'
    runs-on: ubuntu-latest
    env:
        TF_VAR_github_token: ${{ secrets[format('{0}_GITHUB_TOKEN' , github.event.inputs.environment )] }}
        

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: folder_creation_tf/

    steps:
           # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      # Check for terraform version and status
      - name: Terraform Version
        run: terraform -version

      # Run terraform Init 
      - name: Terraform Init
        run: terraform init

      # Run terraform Plan 
      - name: Terraform Plan
        run: terraform plan -var environment="${{ github.event.inputs.environment }}" -var customer_prefix="${{ github.event.inputs.customer_prefix }}"

      # # Run terraform apply 
      # - name: Terragrunt apply
      #   run: terraform apply --auto-approve -var environment="${{ github.event.inputs.environment }}" -var customer_prefix="${{ github.event.inputs.customer_prefix }}"
