name: Terraform CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Generate Public Key
        run: |
          chmod 600 my-private-key.pem
          ssh-keygen -y -f my-private-key.pem > my-public-key.pub
        
      - name: Import EC2 Key Pair
        run: |
          aws ec2 import-key-pair --key-name my-private-key-pem --public-key-material "$(cat my-public-key.pub)" --region ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.9

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # - name: Terraform destroy
      #   run: terraform destroy --auto-approve