name: Terraform CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Save EC2 Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}"> private_key.pem
          pwd
          ls
          chmod 600 private_key.pem
 
      # - name: Move private key to working directory
      #   run: mv private_key.pem .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.9

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Plan        
      #   env:
      #     TF_VAR_private_key_name: private_key.pem

      #   working-directory: /home/runner/work/terraform/terraform
      #   run: |
      #    pwd
      #    ls  
      #    terraform plan -out=tfplan

      # - name: Terraform Apply
      #   env:
      #     TF_VAR_private_key_name: ${{ secrets.EC2_PRIVATE_KEY }}
      #   working-directory: /home/runner/work/terraform/terraform
      #   run: |
      #    pwd
      #    ls 
      #    terraform apply -auto-approve

      - name: Terraform destroy
        run: terraform destroy --auto-approve