name: CI Java Build and ECR Push

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'GitHub repository to checkout (owner/repo format)'
        required: true
        type: string
      ecr_repository:
        description: 'AWS ECR repository name (e.g., my-java-app)'
        required: true
        type: string
      docker_tag:
        description: 'Docker tag for the image'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Java Application
        run: |
          echo "Building Java application..."
          mvn clean package -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifact
          path: target/*.jar

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.ECR_REGISTRY }}/${{ github.event.inputs.ecr_repository }}:${{ github.event.inputs.docker_tag }} .

      - name: Push Docker Image to Amazon ECR
        run: |
          echo "Pushing Docker image..."
          docker push ${{ env.ECR_REGISTRY }}/${{ github.event.inputs.ecr_repository }}:${{ github.event.inputs.docker_tag }}