name: CI Java Build and Docker Push
 
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'GitHub repository to checkout (owner/repo format)'
        required: true
        type: string
      docker_image:
        description: 'Docker image name to push'
        required: true
        type: string
      docker_tag:
        description: 'Docker tag for the image'
        required: true
        type: string
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
 
      - name: Build Java Application
        run: |
          echo "Building Java application..."
          mvn clean package -DskipTests
 
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifact
          path: target/*.jar
 
      - name: Log in to DockerHub
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${DOCKERHUB_USERNAME}/${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }} .
 
      - name: Push Docker Image to Docker Hub
        run: |
          echo "Pushing Docker image..."
          docker push ${DOCKERHUB_USERNAME}/${{ github.event.inputs.docker_image }}:${{ github.event.inputs.docker_tag }}
 