name: Terraform Infra Setup 

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Save EC2 Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}"> private_key.pem
          pwd
          ls
          chmod 600 private_key.pem

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov Static Analysis
        run: |
          checkov -d . --skip-path .github/* --skip-path k8s/*   

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan        
        env:
          TF_VAR_private_key_name: private_key.pem
        working-directory: /home/runner/work/terraform/terraform
        run: |  
         terraform plan

      - name: Terraform Apply
        env:
          TF_VAR_private_key_name: ${{ secrets.EC2_PRIVATE_KEY }}
        working-directory: /home/runner/work/terraform/terraform
        run: |
         export TF_LOG=DEBUG
         export TF_LOG_PATH=log.txt 
         terraform apply -auto-approve

      - name: Upload Terraform logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: ./log.txt

      # - name: Terraform destroy
      #   run: terraform destroy --auto-approve






      # - name: Configure Terraform Credentials
      #   run: |
      #     mkdir -p ~/.terraform.d
      #     cat > ~/.terraform.d/credentials.tfrc.json <<EOF
      #     {
      #       "credentials": {
      #         "app.terraform.io": {
      #           "token": "${{ secrets.TFE_TOKEN }}"
      #           aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      #           aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #           aws-region: ap-south-1
      #         }
      #       }
      #     }
      #     EOF

#       terraform {
#   backend "remote" {
#     organization = "Org-new"
    
#     workspaces {
#       name = "terraform"
#     }
#   }
# }

        # env:
        #   TFE_TOKEN: ${{ secrets.TFE_TOKEN }}